server:
  port: 8090

spring:

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        - id: academic-service
          uri: lb://ACADEMIC-SERVICE
          predicates:
            - Path=/api/v1/academic/**
          filters:
            - RewritePath=/api/v1/academic/(?<segment>.*), /api/v1/${segment}
        
        - id: tasks-service
          uri: lb://TASKS-SERVICE
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - RewritePath=/api/v1/tasks/(?<segment>.*), /api/v1/tasks/${segment}
        
        - id: tutoring-service
          uri: lb://TUTORING-SERVICE
          predicates:
            - Path=/api/v1/tutoring/**
          filters:
            - RewritePath=/api/v1/tutoring/(?<segment>.*), /api/v1/tutoring/${segment}

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,metrics,prometheus
  
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  
  metrics:
    export:
      prometheus:
        enabled: true

# Logging para debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
