spring:
  datasource:
    url: jdbc:h2:mem:testdb_NUEVA;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # Configuración mínima - sin naming strategies complejos
    show-sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE   
server:
  port: 8092

# Configuracion de eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    ip-address: 127.0.0.1